#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/sqm-start.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 10
    procd_close_instance
}

stop_service() {
    /usr/bin/sqm-stop.sh
}

restart() {
    stop
    sleep 1
    start
}
